check-scj: check-hello check-enter-private check-immortal check-immortal2



FIJI_HOME=../../../../
SCJFLAGS="--scj --scj-scope-backing 12m --g-def-immortal-mem 1m"
FIJIFLAGS="--max-threads 5"  # -v 1
	
check-hello:	
	$(FIJI_HOME)/bin/fivmc -o hello $(SCJFLAGS) build/HelloWorld*.class
	./hello
--successLine = "HelloWorld."

#--successLine = "set-up."
#--successLine = "HelloWorld."
#--successLine = "HelloWorld."
#--successLine = "cleanUp."
#--successLine = "teardown."


	
# TODO: check if we need to specify the safelet!!	
check-enter-private:
	$(FIJI_HOME)/bin/fivmc -o enterPrivate $(SCJFLAGS) $(FIJIFLAGS) build/EnterPrivateTest*.class
	./enterPrivate 
--successLine = "EnterPrivateMemory OK."

	

# This is going to fail. 
check-immortal:
	$(FIJI_HOME)/bin/fivmc -o immortalTest $(SCJFLAGS) $(FIJIFLAGS) build/TestImmortal*.class
	./immortalTest 
--successLine = "TestImmortal OK."

	
	


check-immortal2:
	$(FIJI_HOME)/bin/fivmc -o immortalTest2 $(SCJFLAGS) $(FIJIFLAGS) build/ImmortalTest2*.class
	./immortalTest2 
--successLine = "ImmortalMemoryTest2: OK."

	

