FIJI_HOME=../../../../
SCJFLAGS="--scj --scj-safelet HelloWorld  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS1="--scj --scj-safelet MemoryTest  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS2="--scj --scj-safelet TestPrimordial  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS3="--scj --scj-safelet TestPreciseTime  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS4="--scj --scj-safelet TestImmortal  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS5="--scj --scj-safelet EnterPrivateTest  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS6="--scj --scj-safelet ImmortalTest2  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS7="--scj --scj-safelet SCJLock  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS8="--scj --scj-safelet Level0App  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS9="--scj --scj-safelet HelloSCJ  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS11="--scj --scj-safelet TestException000  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS12="--scj --scj-safelet TestJNI900  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS13="--scj --scj-safelet TestMemory504  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS14="--scj --scj-safelet TestSchedule400  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS15="--scj --scj-safelet TestSchedule402  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS16="--scj --scj-safelet TestSchedule404  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS17="--scj --scj-safelet TestSchedule405  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS18="--scj --scj-safelet TestSchedule406  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS19="--scj --scj-safelet TestSchedule409  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS20="--scj --scj-safelet TestSchedule407  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"
SCJFLAGS21="--scj --scj-safelet TestClock600  --scj-scope-backing 3100k --g-def-immortal-mem 5000k --more-opt"




FIJIFLAGS="--max-threads 3" 

#
# FULL SCJ CHECK
#

check-scj: check-scj-hello check-memory check-Primordial check-PreciseTime check-Immortal check-EnterPrivate check-Immortal2 check-SCJLock check-Level0App check-HelloSCJ check-TestMemory501 check-Exception000 check-JNI900 check-TestMemory504 check-Schedule400 check-Schedule402 check-Schedule404 check-Schedule405 check-Schedule406 check-Schedule409 check-Schedule407 check-Clock600
#
#
#

check-scj-hello:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o hello  $(SCJFLAGS)  $(FIJIFLAGS) build
	./hello

check-memory:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o memory  $(SCJFLAGS1)  $(FIJIFLAGS) build
	./memory

check-Primordial:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o Primordial  $(SCJFLAGS2)  $(FIJIFLAGS) build
	./Primordial

check-PreciseTime:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o PreciseTime  $(SCJFLAGS3)  $(FIJIFLAGS) build
	./PreciseTime

check-Immortal:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o Immortal $(SCJFLAGS4)  $(FIJIFLAGS) build
	./Immortal

check-EnterPrivate:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o EnterPrivate $(SCJFLAGS5)  $(FIJIFLAGS) build
	./EnterPrivate

check-Immortal2:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o Immortal2 $(SCJFLAGS6)  $(FIJIFLAGS) build
	./Immortal2

check-SCJLock:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o SCJLock $(SCJFLAGS7)  $(FIJIFLAGS) build
	./SCJLock

check-Level0App:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o Level0App $(SCJFLAGS8)  $(FIJIFLAGS) build
	./Level0App

check-HelloSCJ:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o HelloSCJ $(SCJFLAGS9)  $(FIJIFLAGS) build
	./HelloSCJ

check-TestMemory501:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o TestMemory501 $(SCJFLAGS10)  $(FIJIFLAGS) build
	./TestMemory501

check-Exception000:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o Exception000 $(SCJFLAGS11)  $(FIJIFLAGS) build
	./Exception000

check-JNI900:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o JNI900 $(SCJFLAGS12)  $(FIJIFLAGS) build
	./JNI900

check-TestMemory504:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o TestMemory504 $(SCJFLAGS13)  $(FIJIFLAGS) build
	./TestMemory504

check-Schedule400:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o Schedule400 $(SCJFLAGS14)  $(FIJIFLAGS) build
	./Schedule400

check-Schedule402:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o Schedule402 $(SCJFLAGS15)  $(FIJIFLAGS) build
	./Schedule402

check-Schedule404:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o Schedule404 $(SCJFLAGS16)  $(FIJIFLAGS) build
	./Schedule404

check-Schedule405:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o Schedule405 $(SCJFLAGS17)  $(FIJIFLAGS) build
	./Schedule405

check-Schedule406:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o Schedule406 $(SCJFLAGS18)  $(FIJIFLAGS) build
	./Schedule406

check-Schedule409:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o Schedule409 $(SCJFLAGS19)  $(FIJIFLAGS) build
	./Schedule409

check-Schedule407:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o Schedule407 $(SCJFLAGS20)  $(FIJIFLAGS) build
	./Schedule407

check-Clock600:
	$(RUBY) $(FIJI_HOME)/bin/fivmc  -o Clock600 $(SCJFLAGS21)  $(FIJIFLAGS) build
	./Clock600